add_newline = false
format = """${custom.env}\\[$username$hostname $directory\\]${custom.char}"""

[hostname]
ssh_only = false
show_always = true
format = "@[$hostname](bold cyan)"

[username]
ssh_only = false
show_always = true
format = "[$user](bold cyan)"

[directory]
truncation_length = 1
style = ""
format = "[$path](green)"

[custom.env]
command = "basename $VIRTUAL_ENV"
when = "if [[ -z $VIRTUAL_ENV ]]; then exit 1; else exit 0; fi"
format = "\\($output\\) "

[custom.char]
command = "if [[ `whoami` == 'root' ]]; then echo '#'; else echo '$'; fi"
when = ""
format = "$output "
